### ISSUE TITLE
Fail

### ISSUE THREAD

**Issue by esscardano** [camunda-consulting/docker-camunda-platform#2]
https://github.com/camunda-consulting/docker-camunda-platform/blob/1690f9d13a705812db42edfddc0932b1f1f03866/tomcat-camunda-bpm-ee/Dockerfile#L73

When running Dockerfile, it fails at this line: 

> /bin/sh: can't open 'https://app.camunda.com/nexus/service/local/artifact/maven/redirect?r=camunda-bpm-ee&g=org.camunda.bpm&a=camunda-database-settings&v=7.7.3-ee&p=pom --user=XXXX --password=XXXX'
> Cannot write to '-' (Invalid argument).

**Comment by falko** [comment]
Fixed in https://app.camunda.com/jira/browse/CAM-8375
