### ISSUE TITLE
bug: Install fails / Registry seems to be private 

### ISSUE THREAD

**Issue by ichtestemalwieder** [camunda-consulting/docker-camunda-platform#3]
I would like to test out camunda. The repo makes the impression that it is public, but the Registry seems to require access credentials. I get this (docker) error: 

`Service 'db' failed to build: Get https://registry.camunda.cloud/v2/camunda-bpm-platform-ee/manifests/tomcat-7.10.5: no basic auth credentials`

1.) Please state (in the README), if this is a public repository or not. 
2.) If it is a public repository please provide the image without credentials or publish some guest access credentials. 
3.) If it is a non public repo, please state how I can setup a demo camunda instance with all dependencies 

Thanks.

**Comment by falko** [comment]
Well, the description of the repo says: "Docker images for Camunda BPM Enterprise Edition". Nevertheless, I'll update the README.

Community Edition images can be found on Docker Hub.
See also: https://docs.camunda.org/manual/latest/installation/docker/

**Comment by falko** [comment]
Thank you for the feedback. If you have further suggestions, feel free to send a pull request.

**Comment by ichtestemalwieder** [comment]
thanks!
